export enum EnvNames {
  SERVER_HTTP_PORT = "SERVER_HTTP_PORT",

  MONGODB_URI = "MONGODB_URI",

  REDIS_HOST = "REDIS_HOST",
  REDIS_PORT = "REDIS_PORT",

  RABBITMQ_HOST = "RABBITMQ_HOST",
  RABBITMQ_PORT = "RABBITMQ_PORT",
  RABBITMQ_EVENT_BUS_NAME = "RABBITMQ_EVENT_BUS_NAME",
}
